### ISSUE TITLE
Add to pgxn?

### ISSUE THREAD

**Issue by saolof** [fboulnois/pg_uuidv7#1]
Hi!

This postgres extension is really useful! Would it be possible to add it to pgxn.org for easy installation?

**Comment by fboulnois** [comment]
I created a workflow to publish new version to PGXN. Expect to see `pg_uuidv7` on PGXN soon. Thanks for the suggestion!

**Comment by fboulnois** [comment]
See it published here: https://pgxn.org/dist/pg_uuidv7/1.0.1/
