### ISSUE TITLE
Generated values not always monotonic

### ISSUE THREAD

**Issue by gusbzs** [fboulnois/pg_uuidv7#10]
Hi, thanks for creating this extension!

When I generate multiple UUIDv7 values with the same timestamp component, the resulting values are not always monotonic:
![image](https://github.com/fboulnois/pg_uuidv7/assets/7851513/35189f1f-ef26-4488-b57c-6873ad20a688)

If I sort the generated values, they end up in a different order:
- 018a6bae-69c8-7071-a5a9-6d5305fe0f9c
- 018a6bae-69c8-7332-8334-225b8cf94177
- 018a6bae-69c8-75c7-a4a1-c472293bc553
- 018a6bae-69c8-770d-bbc4-1d878d654e61
- 018a6bae-69c8-7b81-9cdf-71f21523e24d
- 018a6bae-69c8-7bcf-96ee-dc1fbf232699
- 018a6bae-69c8-7c98-8ef0-6f23c3f68da6
- 018a6bae-69c8-7e18-91f1-9d93b1570dd6
- 018a6bae-69c8-7e56-a84d-7043f3879e45
- 018a6bae-69c8-7e6c-acf8-7490e59452d8

Could you please confirm if this is the expected behavior?

Thanks in advance!

**Comment by fboulnois** [comment]
Yes, this is the expected behavior. The final 74 bits after the timestamp are random.

**Comment by gusbzs** [comment]
OK, that's good to know, than you!
