### ISSUE TITLE
"Boundary" UUID function to create UUID from timestamp

### ISSUE THREAD

**Issue by msqr** [fboulnois/pg_uuidv7#11]
I wondered if you would consider adding a function to create "boundary" UUIDs from a given timestamp, to aid in date range query filters. By "boundary" I mean a v7 UUID with the first 48 bits set to a timestamp, but all other non-UUID spec bits set to 0.

For example, a function `uuid_v7_boundary(timestamtz)` could be used like:

```sql
-- "id" column is a v7 UUID
SELECT *
FROM t
WHERE id >= uuid_v7_boundary('2023-09-01Z'::timestamptz)
AND id < uuid_v7_boundary('2023-09-02Z'::timestamptz)
```

I have been using [a SQL function to do this](https://github.com/SolarNetwork/solarnetwork-central/blob/2.42.2/solarnet-db-setup/postgres/postgres-init-common.sql#L326-L345), but I thought it could be a nice feature of this extension.

**Comment by fboulnois** [comment]
Coincidentally I was working on this earlier, so expect this shortly.
