### ISSUE TITLE
Support GreenPlum

### ISSUE THREAD

**Issue by sergeyprokhorenko** [fboulnois/pg_uuidv7#34]
It would be greate to support GreenPlum (version 6.26)

Examples: https://docs.vmware.com/en/VMware-Greenplum/6/greenplum-database/ref_guide-modules-intro.html

**Comment by sergeyprokhorenko** [comment]
https://github.com/open-gpdb/gpuuidv7

**Comment by fboulnois** [comment]
This is out of scope for this project.

**Comment by fboulnois** [comment]
This is out of scope for this project.
