### ISSUE TITLE
PL/pgSQL Version

### ISSUE THREAD

**Issue by shellscape** [fboulnois/pg_uuidv7#5]
Hey there. Thanks for creating this extension! Was curious if it was either performant or possible to create a version of this using [PL/pgSQL](https://github.com/aws/pg_tle/blob/main/docs/06_plpgsql_examples.md) so that it can be used with AWS RDS, Supabase, etc (cloud postgres) and pg_tle.

**Comment by fboulnois** [comment]
There's a pure SQL version available here but it's about [20% slower](https://github.com/fboulnois/pg_uuidv7/blob/main/BENCHMARKS.md) than this extension: https://gist.github.com/kjmph/5bd772b2c2df145aa645b837da7eca74

**Comment by shellscape** [comment]
Good to know, thanks. Sadly we're limited with most Postgres cloud instances

**Comment by fboulnois** [comment]
Closing since there's an existing PL/pgSQL solution.
