### ISSUE TITLE
Add ability to extract the timestamp from uuid value

### ISSUE THREAD

**Issue by k-bx** [fboulnois/pg_uuidv7#6]
Would be nice to have a simple function that could extract the timestamp part of the uuidv7 value.

For now, I've found this ugly hack:

```sql
SELECT to_timestamp(('x' || ltrim((decode(replace(uuid_generate_v7()::text, '-', ''), 'hex'))::text, '\x'))::bit(48)::bigint / 1000);
```

**Comment by fboulnois** [comment]
Check out version 1.1.0, I added the `uuid_v7_to_timestamptz` function.

**Comment by k-bx** [comment]
Perfect, thank you!
